/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import java.awt.Window;
import java.lang.reflect.Method;
import javax.swing.JButton;

/**
 *
 * @author Emanuel Rivera Aguilar Correo: elmenny_32@hotmail.com
 */
public class PantallaMenu extends javax.swing.JFrame {

    /**
     * Creates new form PantallaMenu
     */
    public PantallaMenu() {
        initComponents();
        setOpaque(this, false);
    }

    public static void setOpaque(Window window, boolean opaque) {

        try {

            Class<?> awtUtilsClass = Class.forName("com.sun.awt.AWTUtilities");
            if (awtUtilsClass != null) {

                Method method = awtUtilsClass.getMethod("setWindowOpaque", Window.class, boolean.class);
                method.invoke(null, window, opaque);

            }

        } catch (Exception exp) {
        }

    }
    
    public JButton getBtnhistorial_movimientos() {
        return btnhistorial_movimientos;
    }

    public JButton getBtn_cerrar_sesion() {
        return btn_cerrar_sesion;
    }

    public JButton getBtn_registrar() {
        return btn_registrar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_agregar_prenda = new javax.swing.JLabel();
        btnhistorial_movimientos = new javax.swing.JButton();
        btn_cerrar_sesion = new javax.swing.JButton();
        btn_registrar = new javax.swing.JButton();
        lbl_agregar_prenda3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_agregar_prenda.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_agregar_prenda.setText("Registrar Empleado");
        getContentPane().add(lbl_agregar_prenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 250, -1));

        btnhistorial_movimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/movimientos_-lanczos3 (1).png"))); // NOI18N
        btnhistorial_movimientos.setBorder(null);
        btnhistorial_movimientos.setBorderPainted(false);
        btnhistorial_movimientos.setContentAreaFilled(false);
        getContentPane().add(btnhistorial_movimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        btn_cerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ssion-lanczos3.png"))); // NOI18N
        btn_cerrar_sesion.setBorder(null);
        btn_cerrar_sesion.setBorderPainted(false);
        btn_cerrar_sesion.setContentAreaFilled(false);
        btn_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_sesionActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        btn_registrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icono-registro-lanczos3.png"))); // NOI18N
        btn_registrar.setBorder(null);
        btn_registrar.setBorderPainted(false);
        btn_registrar.setContentAreaFilled(false);
        btn_registrar.setDefaultCapable(false);
        getContentPane().add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 80, 80));

        lbl_agregar_prenda3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_agregar_prenda3.setText("Movimientos de  inventario");
        getContentPane().add(lbl_agregar_prenda3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 300, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_sesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_cerrar_sesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar_sesion;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btnhistorial_movimientos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_agregar_prenda;
    private javax.swing.JLabel lbl_agregar_prenda3;
    // End of variables declaration//GEN-END:variables
}
