/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author elmen
 */
public class PantallaLogin extends javax.swing.JFrame {

    /**
     * Creates new form PantallaLogin
     */
    public PantallaLogin() {
        initComponents();
    }

    public JLabel getLbl_tipo_usu() {
        return lbl_tipo_usu;
    }
    
    public JButton getBtnsignin() {
        return btnsignin;
    }

    public JPasswordField getTextcontra() {
        return textcontra;
    }

    public JTextField getTextnombre() {
        return textnombre;
    }

    public JButton getBtnsalir2() {
        return btnsalir2;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textcontra = new javax.swing.JPasswordField();
        textnombre = new javax.swing.JTextField();
        btnsignin = new javax.swing.JButton();
        btnsalir2 = new javax.swing.JButton();
        lbl_tipo_usu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textcontra.setBackground(new java.awt.Color(136, 136, 188));
        textcontra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textcontra.setForeground(new java.awt.Color(51, 51, 51));
        textcontra.setBorder(null);
        textcontra.setOpaque(false);
        textcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textcontraActionPerformed(evt);
            }
        });
        getContentPane().add(textcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 364, 220, 30));

        textnombre.setBackground(new java.awt.Color(136, 136, 188));
        textnombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        textnombre.setForeground(new java.awt.Color(51, 51, 51));
        textnombre.setBorder(null);
        textnombre.setOpaque(false);
        getContentPane().add(textnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 298, 220, 30));

        btnsignin.setText("INICIAR SESIÓN");
        btnsignin.setBorder(null);
        btnsignin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnsignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 310, 38));

        btnsalir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/equis2-lanczos3.png"))); // NOI18N
        btnsalir2.setBorder(null);
        btnsalir2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(btnsalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 1, 60, 50));

        lbl_tipo_usu.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lbl_tipo_usu.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_tipo_usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 100, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PantallaLogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textcontraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalir2;
    private javax.swing.JButton btnsignin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_tipo_usu;
    private javax.swing.JPasswordField textcontra;
    private javax.swing.JTextField textnombre;
    // End of variables declaration//GEN-END:variables
}
