/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Animacion.Animacion;
import java.awt.Window;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.lang.reflect.Method;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.RowFilter;


/**
 *
 * @author elmen
 */
public class VistaCatalogo extends javax.swing.JFrame {

    /**
     * Creates new form VistaCatalogo
     */
    private boolean btn_arriba_abajo;
    boolean borrar=false;
    
    public VistaCatalogo() {
        initComponents();
        setOpaque(this, false);
        //solo_letras();
        txt_buscar.setText("Escribe para buscar");
        solo_digitos();
        btn_arriba_abajo=false;
        // No se puede mover las columnas de posicion de jTableSeleccionarDatos.
        tabla_inventario.getTableHeader().setReorderingAllowed(false);
    }
    
    public static void setOpaque(Window window, boolean opaque) {

        try {

            Class<?> awtUtilsClass = Class.forName("com.sun.awt.AWTUtilities");
            if (awtUtilsClass != null) {

                Method method = awtUtilsClass.getMethod("setWindowOpaque", Window.class, boolean.class);
                method.invoke(null, window, opaque);

            }

        } catch (Exception exp) {
        }

    }

    public JLabel getLblverimagen() {
        return lblverimagen;
    }

    public void setLblverimagen(JLabel lblverimagen) {
        this.lblverimagen = lblverimagen;
    }   

    public JMenuItem getPopupañadir_al_carro() {
        return popupañadir_al_carro;
    }

    public void setPopupañadir_al_carro(JMenuItem popupañadir_al_carro) {
        this.popupañadir_al_carro = popupañadir_al_carro;
    }

    public JButton getBtncarrito_ventas() {
        return btncarrito_ventas;
    }

    public JButton getBtncerrar_sesion() {
        return btncerrar_sesion;
    }    

    public JLabel getLbl_talla() {
        return lbl_talla;
    }

    public JTextField getTxt_cantidad() {
        return txt_cantidad;
    }

    public JButton getBtn_añadir_lista() {
        return btn_añadir_lista;
    }

    public JTable getjTable_lista_productos() {
        return jTable_lista_productos;
    }

    public JButton getBtn_remover_vestido() {
        return btn_remover_vestido;
    }

    public JLabel getLbl_total_realizar_venta() {
        return lbl_total_realizar_venta;
    }

    public JButton getBtn_realizar_venta() {
        return btn_realizar_venta;
    }

    public JTextField getTxt_buscar() {
        return txt_buscar;
    }

    public JComboBox<String> getjComboBox_opciones() {
        return jComboBox_opciones;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        popupañadir_al_carro = new javax.swing.JMenuItem();
        txt_buscar = new javax.swing.JTextField();
        jComboBox_opciones = new javax.swing.JComboBox<>();
        btncerrar_sesion = new javax.swing.JButton();
        txt_cantidad = new javax.swing.JTextField();
        btn_añadir_lista = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_inventario = new JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex) {

                return false; //Las celdas no son editables.

            }
        };
        btn_remover_vestido = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbl_total_realizar_venta = new javax.swing.JLabel();
        btn_realizar_venta = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_lista_productos = new JTable(){

            public boolean isCellEditable(int rowIndex, int colIndex) {

                return false; //Las celdas no son editables.

            }
        };
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_talla1 = new javax.swing.JLabel();
        btncarrito_ventas = new javax.swing.JButton();
        lbl_talla = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblverimagen = new javax.swing.JLabel();
        lblno_image = new javax.swing.JLabel();

        popupañadir_al_carro.setLabel("Añadir al carrito");
        popupañadir_al_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                popupañadir_al_carroActionPerformed(evt);
            }
        });
        jPopupMenu1.add(popupañadir_al_carro);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_buscarMouseClicked(evt);
            }
        });
        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });
        getContentPane().add(txt_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 180, 30));

        jComboBox_opciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CATEGORIA", "DESCRIPCION", "TALLA", "COLOR" }));
        getContentPane().add(jComboBox_opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 120, 30));

        btncerrar_sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ssion-lanczos3.png"))); // NOI18N
        btncerrar_sesion.setBorderPainted(false);
        btncerrar_sesion.setContentAreaFilled(false);
        btncerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrar_sesionActionPerformed(evt);
            }
        });
        getContentPane().add(btncerrar_sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 100, 80, 70));
        getContentPane().add(txt_cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 120, 30));

        btn_añadir_lista.setText("Añadir a la Lista");
        getContentPane().add(btn_añadir_lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, 150, 30));

        tabla_inventario.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        tabla_inventario.setForeground(new java.awt.Color(153, 153, 255));
        tabla_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_inventario.setToolTipText("");
        tabla_inventario.setComponentPopupMenu(jPopupMenu1);
        tabla_inventario.setRowHeight(30);
        tabla_inventario.setRowMargin(10);
        jScrollPane1.setViewportView(tabla_inventario);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 640, 180));

        btn_remover_vestido.setText("Remover Vestido");
        btn_remover_vestido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_remover_vestidoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_remover_vestido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 130, 40));

        jButton3.setText("Remover Todo");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, 110, 40));

        lbl_total_realizar_venta.setBackground(new java.awt.Color(0, 0, 0));
        lbl_total_realizar_venta.setFont(new java.awt.Font("Calibri Light", 1, 28)); // NOI18N
        lbl_total_realizar_venta.setForeground(new java.awt.Color(255, 255, 255));
        lbl_total_realizar_venta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lbl_total_realizar_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 660, 270, 30));

        btn_realizar_venta.setText("Realizar Venta");
        getContentPane().add(btn_realizar_venta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 690, 180, 30));

        jTable_lista_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod. Producto", "Categoria", "Talla", "Cantidad", "Precio Unitario", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_lista_productos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_lista_productosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable_lista_productos);
        if (jTable_lista_productos.getColumnModel().getColumnCount() > 0) {
            jTable_lista_productos.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTable_lista_productos.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 640, 140));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("TOTAL:   $");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 660, 100, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/listaprod-lanczos3 (1).png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 640, 320));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/parchedeabajo.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 120, 120));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CANTIDAD:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 100, 30));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/prod-lanczos3 (1).png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 650, 210));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/parche-lanczos3 (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, -1, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/parche-lanczos3 (1).png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 100, -1, 70));

        lbl_talla1.setBackground(new java.awt.Color(0, 0, 0));
        lbl_talla1.setFont(new java.awt.Font("Calibri Light", 1, 28)); // NOI18N
        lbl_talla1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_talla1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_talla1.setText("Talla: ");
        getContentPane().add(lbl_talla1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 650, 90, 30));

        btncarrito_ventas.setContentAreaFilled(false);
        getContentPane().add(btncarrito_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 70, 70));

        lbl_talla.setBackground(new java.awt.Color(0, 0, 0));
        lbl_talla.setFont(new java.awt.Font("Calibri Light", 1, 28)); // NOI18N
        lbl_talla.setForeground(new java.awt.Color(255, 255, 255));
        lbl_talla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbl_talla, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 650, 170, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/header1-lanczos3 (1).png"))); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, -1, 180));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/parcheeeeeee.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 240, 160));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo-png.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1150, -1));
        getContentPane().add(lblverimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 390, 390));

        lblno_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/noimage-lanczos3.png"))); // NOI18N
        lblno_image.setText("jLabel5");
        getContentPane().add(lblno_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 390, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void popupañadir_al_carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_popupañadir_al_carroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_popupañadir_al_carroActionPerformed

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void btn_remover_vestidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_remover_vestidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_remover_vestidoActionPerformed

    private void btncerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrar_sesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrar_sesionActionPerformed

    private void jTable_lista_productosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_lista_productosMouseClicked
        // TODO add your handling code here:
        int clic_tabla = jTable_lista_productos.rowAtPoint(evt.getPoint());
        System.out.println(clic_tabla);
        
//        int codigo = (int)tabla.getValueAt(clic_tabla, 0);
//        String nombre = ""+tabla.getValueAt(clic_tabla, 1);
//        double precio = (double)tabla.getValueAt(clic_tabla, 2);
//        Object descripcion = ""+tabla.getValueAt(clic_tabla, 3);
//
// 
//        
//        try{
//            JLabel lbl = (JLabel)tabla.getValueAt(clic_tabla, 4);
//            lblFoto.setIcon(lbl.getIcon());
//        }catch(Exception ex){
//        }
        
        
        
    }//GEN-LAST:event_jTable_lista_productosMouseClicked

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
     
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void txt_buscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_buscarMouseClicked
        txt_buscar.setText("");
        txt_cantidad.setEnabled(false);
        btn_añadir_lista.setEnabled(false);
    }//GEN-LAST:event_txt_buscarMouseClicked

    public void solo_letras(){
        
        txt_buscar.addKeyListener(new KeyAdapter() {
        
            public void keyTyped(KeyEvent e){
                 char c=e.getKeyChar(); 
             
         
                if(Character.isDigit(c)) { 
                    getToolkit().beep(); 

                    e.consume(); 

                   //

                } 
            }
        
        });


    }
    
   private void solo_digitos(){
       txt_cantidad.addKeyListener(new KeyAdapter()
        {
           public void keyTyped(KeyEvent e)
           {
              char caracter = e.getKeyChar();

              // Verificar si la tecla pulsada no es un digito
              if(((caracter < '0') ||
                 (caracter > '9')) &&
                 (caracter != '\b' /*corresponde a BACK_SPACE*/))
              {
                 e.consume();  // ignorar el evento de teclado
              }
           }
        });
   }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCatalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCatalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_añadir_lista;
    private javax.swing.JButton btn_realizar_venta;
    private javax.swing.JButton btn_remover_vestido;
    private javax.swing.JButton btncarrito_ventas;
    private javax.swing.JButton btncerrar_sesion;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox_opciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_lista_productos;
    private javax.swing.JLabel lbl_talla;
    private javax.swing.JLabel lbl_talla1;
    private javax.swing.JLabel lbl_total_realizar_venta;
    private javax.swing.JLabel lblno_image;
    private javax.swing.JLabel lblverimagen;
    public static javax.swing.JMenuItem popupañadir_al_carro;
    public static javax.swing.JTable tabla_inventario;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_cantidad;
    // End of variables declaration//GEN-END:variables
}
